AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC and EC2 instance creation template'

Resources:
  # VPC
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: MyVPC

  # Internet Gateway
  MyInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: MyInternetGateway

  # Attach Internet Gateway to VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MyVPC
      InternetGatewayId: !Ref MyInternetGateway

  # Private Subnet
  MyPrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: MyPrivateSubnet

  # Security Group
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "Allow SSH"
      GroupDescription: "Allow SSH access from anywhere"
      VpcId: !Ref MyVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  # EC2 Instance
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-078701cc0905d44e4
      SubnetId: !Ref MyPrivateSubnet
      SecurityGroupIds: 
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: MyEC2Instance

Outputs:
  VPC:
    Description: Referenced to the created VPC
    Value: !Ref MyVPC
    Export:
      Name: MyVPC-ID

  PrivateSubnet:
    Description: Referenced to the private subnet
    Value: !Ref MyPrivateSubnet
    Export:
      Name: MyPrivateSubnet-ID

  EC2Instance:
    Description: EC2 Instance ID
    Value: !Ref MyEC2Instance